github: https://github.com/Connerrrrr
repository: https://github.com/Connerrrrr/Connerrrrr.github.io
website: https://connerrrrr.github.io
chatbot: https://github.com/Connerrrrr/Closed-Domain-Chatbot
nutrition: https://github.com/Connerrrrr/nutrition-label-recognizer
scrapy: https://github.com/Connerrrrr/Scrapy_douban